config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, except: [:index] do
    resources :reservations, only: %i[create show destroy]
  end
  resources :racoons, except: %i[index new edit update] do
    resources :reviews, only: %i[index new create edit update destroy]
    resources :services, only: %i[new create edit update]
    resources :disponibilities, only: %i[new create update destroy]
  end
  resources :services, only: %i[destroy]

  # Defines the root path route ("/")
  # root "articles#index"
  get "/style", to: 'pages#style'
  get "/legal", to: 'pages#legal'
  get "/about", to: 'pages#about'
  get "/users/:id/dashboard", to: 'users#dashboard', as: :user_dashboard
  patch "/reservation/:id/accept", to: 'reservations#accept', as: :reservation_accept
  patch "/reservation/:id/refuse", to: 'reservations#refuse', as: :reservation_refuse
end

app/views/shared/__cards_racoon.html.erb
<div class="cards">
  <% @racoons.each do |racoon| %>
  <div>
    <div class="card">
      <%= link_to "", racoon_path(racoon) %>
      <div class="d-flex-column">
        <div class="card-img" style="background-image: url('https://t4.ftcdn.net/jpg/04/50/96/23/240_F_450962330_w4RDU0GCIeKy0QvSxBuJ0MHp4mkuXWts.jpg')"></div>
          <div class="card-content">
              <div class="card-title"><%= racoon.user.username%></div>
              <div class="card-address"><%= racoon.user.city%></div>
              <i class="fa-solid fa-star"></i>
              <div class="card-rating">4.8</div>
              <div class="card-price">price</div>

            </div>
        </div>
      </div>
    </div>
  <% end  %>
</div>

app/views/shared/__cards_racoons.html.erb
<div class="cards">
  <% @racoons.each do |racoon| %>
  <div>
    <div class="card">
      <%= link_to "", racoon_path(racoon) %>
      <div class="d-flex-column">
        <div class="card-img" style="background-image: url('https://t4.ftcdn.net/jpg/04/50/96/23/240_F_450962330_w4RDU0GCIeKy0QvSxBuJ0MHp4mkuXWts.jpg')"></div>
          <div class="card-content">
              <div class="card-title"><%= racoon.user.username%></div>
              <div class="card-address"><%= racoon.user.city%></div>
              <div class="card-rating"><i class="fa-solid fa-star"></i>4.8</div>
              <div class="card-price">price</div>
            </div>
        </div>
      </div>
    </div>
  <% end  %>
</div>

app/views/shared/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_cards_racoons.html.erb
<div class="cards">
  <% @racoons.each do |racoon| %>
  <div>
    <div class="card">
      <%= link_to "", racoon_path(racoon) %>
      <div class="d-flex-column">
          <% if racoon.user.photo.attached? %>
        <div class="card-img" style="background-image : url(<%= cl_image_path racoon.user.photo.key, height: 300, width: 400, crop: :fill %>)">
          <% else %>
        <div class="card-img" style="background-image : url('https://t4.ftcdn.net/jpg/04/50/96/23/240_F_450962330_w4RDU0GCIeKy0QvSxBuJ0MHp4mkuXWts.jpg')">
          <% end %>
        </div>
          <div class="card-content">
            <div class="card-title"><%= racoon.user.username%></div>
            <div class="card-address"><%= racoon.user.city%></div>
            <div class="card-rating"><i class="fa-solid fa-star"></i>4.8</div>
            <div class="card-price"><%= racoon.service.price.round(2) %>€</div>
          </div>
        </div>
      </div>
    </div>
  <% end  %>
  </div>
</div>

app/views/shared/_footer.html.erb
<%# FOOTER %>
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-4 ps-md-0 mb-30">
        <ul id="about-us-padding" class="ul-secondary ul-flex-col-end">
          <li><%= link_to "About us", "/about" %></li>
          <li><%= link_to "Legal notice", "/legal" %></li>
          <li><%= link_to "Press", "/#" %></li>
        </ul>
      </div>
      <div class="col-4 ps-md-0 mb-30">
        <ul class="ul-secondary ul-flex-col-center">
          <li><%= link_to "Contact us", "/", class: "" %></li>
          <div id="icons-hover" class="d-flex">
            <div>
              <li><%= link_to "", "/", class: "fa-brands fa-facebook" %></li>
            </div>
            <div>
              <li><%= link_to "", "/", class: "fa-brands fa-twitter" %></li>
            </div>
            <div>
              <li><%= link_to "", "/", class: "fa-brands fa-instagram" %></li>
            </div>
          </div>
        </ul>
      </div>
      <div class="col-4 ps-md-0 mb-30">
        <ul class="ul-secondary .ul-flex-col-start">
          <li><%= link_to "Support us !", "/", class: "" %></li>
          <li><%= link_to "Suscribe", "/", class: "btn btn-secondary" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for [@racoon, @disponibility] do |f| %>
  <%= f.input :date, as: :string, input_html: { data: { controller: 'flatpickr' } } %>
  <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<%# NAVBAR %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

  <%# HOME-ICON %>
    <div class="col-4">
      <a class="navbar-brand" href="/">
        <img src="https://res.cloudinary.com/dc4rntncg/image/upload/v1685631465/racoon_logo_v1-removebg-preview_lv5eth.png" alt="racoon">
      </a>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <%# /HOME-ICON %>

  <%# SEARCH_BAR %>
    <div class="col-4">
      <%= form_with url: root_path, method: :get do %>
        <div class="search-form-control form-group">
          <div id="form" class="search-form-control form-group">
            <%= text_field_tag :query, params[:query], class: "form-control string required" %>
              <%= button_tag type: 'submit', class: "btn text-white btn-flat" do %>
                <i class="fas fa-search"></i>
              <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <%# /SEARCH_BAR %>

  <%# DASHBOARD + AVATAR %>
    <div class="col-4">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Dashboard", user_dashboard_path(current_user.id), class: "btn btn-primary" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "down", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag 'https://t4.ftcdn.net/jpg/04/50/96/23/240_F_450962330_w4RDU0GCIeKy0QvSxBuJ0MHp4mkuXWts.jpg' , class: "avatar dropdown-toggle", id: "down", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="down">
                <%= link_to "Action", "#" ,  class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <%# /DASHBOARD + AVATAR %>

  </div>
</div>